dataset_name: Diabetes
bootstrap_fraction: 0.8
n_estimators: 200
computation_mode: error_analysis
num_runs: 1
runs_seed_lst: [100]
sensitive_attributes_dct: {'gender': 'Female', 'race': ['AfricanAmerican', 'Other', 'Hispanic', 'Asian'], 'gender & race': None}